// <auto-generated />
namespace ADManageSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class upadteUser10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(upadteUser10));
        
        string IMigrationMetadata.Id
        {
            get { return "202009060705388_upadteUser-1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
